name: flutter_map_supercluster
description: Very fast Marker clustering for flutter_map. Supports efficient adding/removing of Markers.
version: 5.0.0

homepage: https://github.com/rorystephenson/flutter_map_supercluster

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  async: ^2.11.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_map: ^8.2.1
  flutter_map_marker_popup: ^8.0.1
  latlong2: ^0.9.0
  provider: ^6.0.5
  supercluster: ^3.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
